apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-a
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}-a
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-b
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}-b
  type: ClusterIP


